module.exports = {
  CONNECTION: 'connection',
  PARTNER_OUT: 'PARTNER_OUT',
  LEAVE_ROOM: 'LEAVE_ROOM',
  MESSAGE: 'MESSAGE',
  TYPING: 'TYPING',
  STOP_TYPING: 'STOP_TYPING',
  MARK_TYPING: 'MARK_TYPING',
  REMOVE_MARK_TYPING: 'REMOVE_MARK_TYPING',
  DISCONNECT: 'disconnect',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE'
};
